######################## default configuration ####################
baseURL = "https://bughunter0xff.github.io/website-demo/"
title = "Therefore Technologies"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
primary_color = "#90EE90"
